/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_systemui_utils_FrostedGlassUtil */

#ifndef _Included_com_android_systemui_utils_FrostedGlassUtil
#define _Included_com_android_systemui_utils_FrostedGlassUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_systemui_utils_FrostedGlassUtil
 * Method:    clearColor
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_android_systemui_utils_FrostedGlassUtil_clearColor
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_android_systemui_utils_FrostedGlassUtil
 * Method:    imageBlur
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_android_systemui_utils_FrostedGlassUtil_imageBlur
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_android_systemui_utils_FrostedGlassUtil
 * Method:    boxBlur
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_android_systemui_utils_FrostedGlassUtil_boxBlur
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_android_systemui_utils_FrostedGlassUtil
 * Method:    stackBlur
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_android_systemui_utils_FrostedGlassUtil_stackBlur
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_android_systemui_utils_FrostedGlassUtil
 * Method:    oilPaint
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_android_systemui_utils_FrostedGlassUtil_oilPaint
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_android_systemui_utils_FrostedGlassUtil
 * Method:    colorWaterPaint
 * Signature: (Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_android_systemui_utils_FrostedGlassUtil_colorWaterPaint
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
